import train_configs.config1
import train_configs.config2
import train_configs.config3
import train_configs.config4
import train_configs.config5
import train_configs.config6
import train_configs.config7
import train_configs.config8
import train_configs.config9
import train_configs.config10
import train_configs.config11
import train_configs.config12
import train_configs.config13
import train_configs.config14
import train_configs.config15
## work only from here
import train_configs.config16
import train_configs.config17
import train_configs.config18
import train_configs.config19
